"""Helper: write the welcome_popup test file cleanly (avoids shell quoting issues)."""
import pathlib

TEST_FILE = pathlib.Path(__file__).parent.parent / "tests" / "test_welcome_popup.py"

content = (
    '"""\n'
    "Browser tests - Subscribe confirmation popup behaviour.\n"
    "\n"
    "Ghost Portal's native 'Now check your email!' modal handles both subscribe\n"
    "and sign-in confirmation. The custom Welcome Aboard overlay has been removed.\n"
    "\n"
    "These tests verify:\n"
    "  1. The custom #bt-welcome-overlay is NOT present on the page at all.\n"
    "  2. Ghost Portal is still active and functional.\n"
    "\n"
    "Run:\n"
    "    source .venv/bin/activate\n"
    "    pytest tests/test_welcome_popup.py -v\n"
    '"""\n'
    "\n"
    "import pytest\n"
    "from playwright.sync_api import sync_playwright, Page\n"
    "\n"
    "BASE_URL = 'https://beyondtomorrow.world'\n"
    "\n"
    "\n"
    "@pytest.fixture(scope='module')\n"
    "def browser():\n"
    "    with sync_playwright() as p:\n"
    "        b = p.chromium.launch(headless=True)\n"
    "        yield b\n"
    "        b.close()\n"
    "\n"
    "\n"
    "@pytest.fixture\n"
    "def page(browser):\n"
    "    ctx = browser.new_context()\n"
    "    pg = ctx.new_page()\n"
    "    pg.goto(BASE_URL, wait_until='domcontentloaded', timeout=30000)\n"
    "    pg.wait_for_timeout(1500)\n"
    "    yield pg\n"
    "    ctx.close()\n"
    "\n"
    "\n"
    "class TestCustomPopupRemoved:\n"
    '    """The custom Welcome Aboard overlay must be completely absent."""\n'
    "\n"
    "    def test_custom_overlay_not_in_dom(self, page: Page):\n"
    '        """#bt-welcome-overlay must not exist anywhere in the DOM."""\n'
    '        overlay = page.query_selector("#bt-welcome-overlay")\n'
    "        assert overlay is None, (\n"
    "            '#bt-welcome-overlay found in DOM - custom popup was not fully removed'\n"
    "        )\n"
    "\n"
    "    def test_custom_popup_css_not_injected(self, page: Page):\n"
    '        """No bt-welcome-* CSS rules should be present in the page."""\n'
    "        has_css = page.evaluate(\n"
    "            '() => {'\n"
    "            '  for (const sheet of document.styleSheets) {'\n"
    "            '    try {'\n"
    "            '      for (const rule of sheet.cssRules) {'\n"
    "            \"        if (rule.selectorText && rule.selectorText.includes('bt-welcome')) return true;\"\n"
    "            '      }'\n"
    "            '    } catch (e) {}'\n"
    "            '  }'\n"
    "            '  return false;'\n"
    "            '}'\n"
    "        )\n"
    "        assert not has_css, (\n"
    "            'bt-welcome-* CSS rules still present - custom popup styles not removed'\n"
    "        )\n"
    "\n"
    "    def test_confetti_script_not_loaded(self, page: Page):\n"
    '        """canvas-confetti must not be loaded."""\n'
    "        has_confetti = page.evaluate(\n"
    "            \"() => typeof window.confetti !== 'undefined'\"\n"
    "        )\n"
    "        assert not has_confetti, (\n"
    "            'canvas-confetti is still loaded - popup script not fully removed'\n"
    "        )\n"
    "\n"
    "    def test_no_overlay_after_wait(self, page: Page):\n"
    '        """Overlay remains absent after 3 seconds (no deferred injection)."""\n'
    "        page.wait_for_timeout(3000)\n"
    '        overlay = page.query_selector("#bt-welcome-overlay")\n'
    "        assert overlay is None, (\n"
    "            '#bt-welcome-overlay appeared after page load - deferred injection detected'\n"
    "        )\n"
    "\n"
    "\n"
    "class TestGhostPortalIntact:\n"
    '    """Ghost Portal must still be present and functional."""\n'
    "\n"
    "    def test_portal_script_loaded(self, page: Page):\n"
    '        """Ghost Portal script must be referenced in the page source."""\n'
    "        content = page.content()\n"
    "        assert 'portal' in content.lower(), (\n"
    "            'Ghost Portal script not found in page - Portal may be broken'\n"
    "        )\n"
    "\n"
    "    def test_portal_trigger_present(self, page: Page):\n"
    '        """At least one subscribe/portal trigger element must be on the page."""\n'
    "        triggers = page.query_selector_all(\n"
    "            '[data-portal], [data-members-form], a[href*=\"#/portal\"], '\n"
    "            '.gh-portal-trigger, button[data-members-link]'\n"
    "        )\n"
    "        assert len(triggers) > 0, (\n"
    "            'No subscribe/portal trigger elements found on the page'\n"
    "        )\n"
)

TEST_FILE.write_text(content, encoding="utf-8")
print(f"Written {len(content)} chars to {TEST_FILE}")
